### ISSUE TITLE
Multi-select objects so you can delete multiple with one click

### ISSUE THREAD

**Issue by lastnameswayne** [realm/realm-flipper-plugin#106] opened 2022-09-08 13:13 UTC
It would be helpful if users were able to select multiple objects to perform operations on them, such as deleting. This will make it easier to delete multiple objects, as you don't have to delete each one individually.

**Comment by gagik** [comment] 2023-01-06 14:22
Duplicate of https://github.com/realm/realm-flipper-plugin/issues/100.

**Closed by gagik** 2023-01-06 14:22 UTC
Labels: enhancement, O-Community
